/*
 * Copyright 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ivianuu.essentials.material.icons.twotone

import com.ivianuu.essentials.composehelpers.vector.VectorAsset
import com.ivianuu.essentials.material.icons.path
import com.ivianuu.essentials.material.icons.group
import com.ivianuu.essentials.material.icons.Icons

import com.ivianuu.essentials.material.icons.lazyMaterialIcon

val Icons.TwoTone.GridOff: VectorAsset by lazyMaterialIcon {
    path(fillAlpha = 0.3f) {
        moveTo(20.0f, 14.0f)
        verticalLineToRelative(-4.0f)
        horizontalLineToRelative(-4.0f)
        verticalLineToRelative(2.89f)
        lineTo(17.11f, 14.0f)
        close()
        moveTo(10.0f, 12.55f)
        lineTo(10.0f, 14.0f)
        horizontalLineToRelative(1.45f)
        close()
        moveTo(14.0f, 10.0f)
        horizontalLineToRelative(-0.89f)
        lineToRelative(0.89f, 0.89f)
        close()
        moveTo(19.11f, 16.0f)
        lineToRelative(0.89f, 0.89f)
        lineTo(20.0f, 16.0f)
        close()
        moveTo(8.0f, 4.0f)
        horizontalLineToRelative(-0.89f)
        lineToRelative(0.89f, 0.89f)
        close()
        moveTo(14.0f, 8.0f)
        lineTo(14.0f, 4.0f)
        horizontalLineToRelative(-4.0f)
        verticalLineToRelative(2.89f)
        lineTo(11.11f, 8.0f)
        close()
        moveTo(16.0f, 4.0f)
        horizontalLineToRelative(4.0f)
        verticalLineToRelative(4.0f)
        horizontalLineToRelative(-4.0f)
        close()
        moveTo(10.0f, 16.0f)
        verticalLineToRelative(4.0f)
        horizontalLineToRelative(4.0f)
        verticalLineToRelative(-3.45f)
        lineToRelative(-0.55f, -0.55f)
        close()
        moveTo(4.0f, 10.0f)
        verticalLineToRelative(4.0f)
        horizontalLineToRelative(4.0f)
        verticalLineToRelative(-3.45f)
        lineTo(7.45f, 10.0f)
        close()
        moveTo(16.0f, 20.0f)
        horizontalLineToRelative(1.45f)
        lineTo(16.0f, 18.55f)
        close()
        moveTo(4.0f, 16.0f)
        horizontalLineToRelative(4.0f)
        verticalLineToRelative(4.0f)
        lineTo(4.0f, 20.0f)
        close()
        moveTo(4.0f, 6.55f)
        lineTo(4.0f, 8.0f)
        horizontalLineToRelative(1.45f)
        close()
    }
    path {
        moveTo(8.0f, 4.0f)
        verticalLineToRelative(0.89f)
        lineToRelative(2.0f, 2.0f)
        lineTo(10.0f, 4.0f)
        horizontalLineToRelative(4.0f)
        verticalLineToRelative(4.0f)
        horizontalLineToRelative(-2.89f)
        lineToRelative(2.0f, 2.0f)
        lineTo(14.0f, 10.0f)
        verticalLineToRelative(0.89f)
        lineToRelative(2.0f, 2.0f)
        lineTo(16.0f, 10.0f)
        horizontalLineToRelative(4.0f)
        verticalLineToRelative(4.0f)
        horizontalLineToRelative(-2.89f)
        lineToRelative(2.0f, 2.0f)
        lineTo(20.0f, 16.0f)
        verticalLineToRelative(0.89f)
        lineToRelative(2.0f, 2.0f)
        lineTo(22.0f, 4.0f)
        curveToRelative(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f)
        lineTo(5.11f, 2.0f)
        lineToRelative(2.0f, 2.0f)
        lineTo(8.0f, 4.0f)
        close()
        moveTo(16.0f, 4.0f)
        horizontalLineToRelative(4.0f)
        verticalLineToRelative(4.0f)
        horizontalLineToRelative(-4.0f)
        lineTo(16.0f, 4.0f)
        close()
        moveTo(1.41f, 1.14f)
        lineTo(0.0f, 2.55f)
        lineToRelative(2.0f, 2.0f)
        lineTo(2.0f, 20.0f)
        curveToRelative(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f)
        horizontalLineToRelative(15.45f)
        lineToRelative(2.01f, 2.01f)
        lineToRelative(1.41f, -1.41f)
        lineTo(1.41f, 1.14f)
        close()
        moveTo(10.0f, 12.55f)
        lineTo(11.45f, 14.0f)
        lineTo(10.0f, 14.0f)
        verticalLineToRelative(-1.45f)
        close()
        moveTo(4.0f, 6.55f)
        lineTo(5.45f, 8.0f)
        lineTo(4.0f, 8.0f)
        lineTo(4.0f, 6.55f)
        close()
        moveTo(8.0f, 20.0f)
        lineTo(4.0f, 20.0f)
        verticalLineToRelative(-4.0f)
        horizontalLineToRelative(4.0f)
        verticalLineToRelative(4.0f)
        close()
        moveTo(8.0f, 14.0f)
        lineTo(4.0f, 14.0f)
        verticalLineToRelative(-4.0f)
        horizontalLineToRelative(3.45f)
        lineToRelative(0.55f, 0.55f)
        lineTo(8.0f, 14.0f)
        close()
        moveTo(14.0f, 20.0f)
        horizontalLineToRelative(-4.0f)
        verticalLineToRelative(-4.0f)
        horizontalLineToRelative(3.45f)
        lineToRelative(0.55f, 0.55f)
        lineTo(14.0f, 20.0f)
        close()
        moveTo(16.0f, 20.0f)
        verticalLineToRelative(-1.45f)
        lineTo(17.45f, 20.0f)
        lineTo(16.0f, 20.0f)
        close()
    }
}
