include(
    ":essentials",
    ":essentials-app",
    ":essentials-app-glide",
    ":essentials-compiler",
    ":essentials-picker",
    ":essentials-shell",
    ":essentials-test",
    ":essentials-android-test",
    ":ktuples",
    ":sample"
)