include(
    ":essentials",
    ":essentials-about",
    ":essentials-apps",
    ":essentials-apps-coil",
    ":essentials-apps-ui",
    ":essentials-compiler",
    ":essentials-gestures",
    ":essentials-hidenavbar",
    ":essentials-picker",
    ":essentials-securesettings",
    ":essentials-shell",
    ":essentials-test",
    ":essentials-work",
    ":sample"
)