include(
    ":essentials",
    ":essentials-app",
    ":essentials-app-glide",
    ":essentials-compiler",
    ":essentials-hidenavbar",
    ":essentials-picker",
    ":essentials-securesettings",
    ":essentials-shell",
    ":essentials-test",
    ":essentials-work",
    ":ktuples",
    ":sample"
)